- hosts: machine1
  become: yes
  tasks:
    - name: Remove the proxy so that we can run kubeadm
      shell: mv /etc/environment ~ 2> /dev/null || true; mv /etc/profile.d/proxy.sh ~ 2> /dev/null || true

    - name: initialize the cluster
      shell: bash -c "kubeadm reset -f; kubeadm init --pod-network-cidr=10.244.0.0/16  >> cluster_initialized.txt"
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Add the proxy back to deploy our network model
      shell: cp ~/proxy.sh /etc/profile.d/ 2> /dev/null || true; sed s'/export//g' ~/proxy.sh  >> /etc/environment || true

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: source /etc/environment || true; bash -c "kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n') >> pod_network_setup.txt"
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
    
    - name: install kubernetes dashboard
      become: yes
      become_user: ubuntu
      shell: source /etc/environment || true; bash -c "kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml >> create_dashboard_setup.txt"
      args:
        chdir: $HOME
        creates: create_dashboard_setup.txt
    



       
